"""dependency-cruiser architecture/import-rule sensor (JS/TS)."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from codescan.shared.config import VENDOR_EXCLUDES
from codescan.shared.runner import die, find_upward, have, print_topn, run

# Starter config written by `codescan arch --init`. A pragmatic baseline that
# enforces vertical-slice boundaries (no cross-feature imports in `src/features/`)
# and skips vendor/cache dirs that match the rest of codescan's exclusions.
# Project owners edit this to add domain rules; codescan only generates, never
# overwrites (refuse — explicit `rm .dependency-cruiser.cjs` to regenerate).
_STARTER_CONFIG: str = """\
/** @type {import('dependency-cruiser').IConfiguration} */
// Generated by `codescan arch --init`. Edit freely; codescan never overwrites.
module.exports = {
  extends: ["dependency-cruiser/configs/recommended-strict"],
  options: {
    doNotFollow: { path: "__DONT_FOLLOW__" },
    tsConfig: { fileName: "tsconfig.json" },
    enhancedResolveOptions: { exportsFields: ["exports"] },
  },
  forbidden: [
    // Vertical-slice: cross-feature imports belong in `features/shared/`, not directly.
    {
      name: "no-cross-feature-imports",
      severity: "warn",
      from: { path: "^src/features/([^/]+)/" },
      to:   { path: "^src/features/([^/]+)/", dependencyTypes: ["import"] },
    },
  ],
};
"""


def _starter_dont_follow() -> str:
    """Vendor dirs derived from the shared VENDOR_EXCLUDES list (single source of truth)."""
    return "|".join(VENDOR_EXCLUDES)


def _write_starter_config(root: Path) -> tuple[Path, str]:
    """Write the starter config; never overwrite. Returns (path, status)."""
    target = root / ".dependency-cruiser.cjs"
    if target.exists():
        return target, "exists"
    target.write_text(_STARTER_CONFIG.replace("__DONT_FOLLOW__", _starter_dont_follow()))
    return target, "created"


def _is_violation(ln: str) -> bool:
    """Check if a depcruiser output line looks like a violation."""
    low = ln.lower()
    return "error" in low or "warn" in low or "✖" in ln or "→" in ln


def _root_for(path: Path) -> Path:
    """Find the JS project/config root for dependency-cruiser."""
    return (
        find_upward(path, ".dependency-cruiser.cjs")
        or find_upward(path, ".dependency-cruiser.js")
        or find_upward(path, "package.json")
        or (path if path.is_dir() else path.parent).expanduser().resolve()
    )


def arch_payload(
    path: Path, target: str | None, *, include_findings: bool = True
) -> tuple[int, dict[str, Any], str]:
    """Return the dependency-cruiser result payload without printing."""
    tool = "depcruise" if have("depcruise") else "dependency-cruiser"
    payload: dict[str, Any] = {
        "command": "arch",
        "schema_version": 1,
        "tool": tool,
        "path": str(path),
        "status": "ok",
        "counts": {"violations": 0},
        "findings": [],
        "findings_omitted": not include_findings,
        "truncated": False,
    }
    if not have(tool):
        payload["status"] = "missing_tool"
        payload["error"] = "dependency-cruiser not installed"
        return 2, payload, "dependency-cruiser not installed"
    root = _root_for(path)
    payload["root"] = str(root)
    configs = [root / ".dependency-cruiser.cjs", root / ".dependency-cruiser.js"]
    cfg = next((candidate for candidate in configs if candidate.exists()), None)
    if cfg is None:
        payload["status"] = "skipped"
        payload["reason"] = f"no .dependency-cruiser.cjs/.js in {root}"
        return 1, payload, str(payload["reason"])
    cruise_target = target or "src"
    payload["target"] = cruise_target
    payload["config"] = str(cfg)
    rc, out, err = run([tool, "--config", str(cfg), cruise_target], cwd=root)
    lines = [ln for ln in (out or "").splitlines() if ln.strip()]
    lines = [ln for ln in lines if _is_violation(ln)]
    if rc != 0 and not lines:
        payload["status"] = "error"
        payload["error"] = err.strip()
        return 2, payload, err.strip()
    findings = [{"text": line} for line in lines[:40]] if include_findings else []
    payload.update(
        {
            "counts": {"violations": len(lines)},
            "findings": findings,
            "findings_omitted": not include_findings,
            "truncated": include_findings and len(lines) > len(findings),
        }
    )
    return 0, payload, ""


def cmd_arch(args: argparse.Namespace) -> int:
    """dependency-cruiser: validate import-graph rules. Requires .dependency-cruiser.cjs/.js."""
    if getattr(args, "init", False):
        # --init is the only path that may write; refuse if any cruft exists.
        root = _root_for(Path(args.path))
        target, status = _write_starter_config(root)
        if status == "exists":
            print(f"exists, not overwritten: {target}", file=sys.stderr)
            print("  rm it (and commit-history the change) to regenerate", file=sys.stderr)
            return 1
        print(f"wrote: {target}")
        print("  edit me: drop in your domain rules under `forbidden:`")
        return 0
    path = Path(args.path)
    rc, payload, error = arch_payload(path, args.target)
    if payload["status"] == "missing_tool":
        die("dependency-cruiser not installed", 2)
    if getattr(args, "json", False):
        print(json.dumps(payload, indent=2, ensure_ascii=False))
        return 0 if payload["status"] in ("ok", "skipped") else rc
    if payload["status"] == "skipped":
        print(f"{error} — skipping arch rules", file=sys.stderr)
        print(
            "  bootstrap: codescan arch --init (writes a starter, never overwrites)",
            file=sys.stderr,
        )
        return rc
    if payload["status"] == "error":
        print(f"dependency-cruiser error: {error}", file=sys.stderr)
        return rc
    print(f"== dependency-cruiser on {payload['root']}/{payload['target']} ==")
    print(f"output lines: {payload['counts']['violations']}")
    print_topn([str(item.get("text", "")) for item in payload["findings"]])
    return 0
